server:
  port: 8081

spring:
  application:
    name: display

# Hystrix 설정
hystrix :
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000  # 해당 타임 아웃 시간 이후 인 경우 fallbackMethod 실행
      circuitBreaker:   # circuit open 설정
        requestVolumeThreshold: 1   # 몇개의 에러가 발생 했는지 여부 : default 20
        errorThresholdPercentage: 50 # 총 요청 개수에서 해당 퍼센테이지 이상일 때 Open : default 50
    FeignProductRemoteService#getProductInfo(String): # Feign 사용시 Custom hystrix 설정
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # default 1,000ms
      circuitBreaker:
        requestVolumeThreshold: 1
        errorThresholdPercentage: 5

# Ribbon 설정

product:
  ribbon:
#    listOfServers: localhost:8082, localhost:7777 # Ribbon 에서 호출 할 Server URL 목록 RoundRobin 방식으로 호출
    MaxAutoRetries: 0  # 재시도 횟수 ( 실패한 서버외 다른 서버 ) : retry libraries 필요
    MaxAutoRetriesNextServer: 1 # 주의: Hystrix가  Ribbon을 감싸고 있을 경우 Retry를 설정하더라도 즉시 에러를 반환 한다.


eureka:
  instance:
    prefer-ip-address: true # eureka 서버에 hostname 대신 IP로 등록한다
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}  # eureka server 서비스 등록

feign:
  hystrix:
    enabled: true
